logLevel: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
# sub key will be file OR directory, not both.  
  file:
    # filename: /etc/traefik/tls.yml
    directory: /etc/traefik/dynaConfs
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    defaultRule: "HostRegexp({{ index .Labels \"com.docker.compose.service\"}}.traefik.me,{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me)"

# 啟用實驗性插件
experimental:
  plugins:
    traefik-jwt-plugin:
      moduleName: "github.com/traefik-plugins/traefik-jwt-plugin"
      version: "v0.9.0"

http:
  middlewares:
    my-traefik-jwt-plugin:
      plugin:
        traefik-jwt-plugin:
          JwtHeaders:
            X-Subject: sub
          Keys:
            - http://authentication-backend:3001/authentication-backend/jwt/jwks.json
            - |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
              vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
              aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
              tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
              e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
              V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
              MwIDAQAB
              -----END PUBLIC KEY-----
          OpaAllowField: allow
          OpaBody: "true"
          OpaHeaders:
            X-Allowed: allow
          OpaHttpStatusField: allow_status_code
          OpaResponseHeaders:
            X-Allowed: allow
          OpaUrl: http://opa:8181/v1/data/authz
          PayloadFields:
            - exp
          Required: "true"
# static configuration
# core:
#   defaultRuleSyntax: v2